---
# Definition of connected endpoints in the fabric.
port_profiles:
    # Port profile name.
  - profile: L2-Trunk-to-CE
    # Set adapter speed in the format `<interface_speed>` or `forced <interface_speed>` or `auto <interface_speed>`.
    # speed: <str>
    mode: trunk
    port_channel:
      mode: active

routers:
- name: ce1
  adapters:
  - endpoint_ports: ['Ethernet1', 'Ethernet2']
    switches: ['MCI-CTFSTL-LF01a', 'MCI-CTFSTL-LF01b']
    switch_ports: ['Ethernet20', 'Ethernet20']
    profile: L2-Trunk-to-CE
    vlans: 10,11,12,21,22,101,111
- name: ce2
  adapters:
  - endpoint_ports: ['Ethernet1', 'Ethernet2']
    switches: ['MCI-CTFSTL-LF02a', 'MCI-CTFSTL-LF02b']
    switch_ports: ['Ethernet20', 'Ethernet20']
    profile: L2-Trunk-to-CE
    vlans: 10,11,12,21,22,102,122
- name: ce34
  adapters:
  - endpoint_ports: ['Ethernet3/5', 'Ethernet3/6']
    switches: ['MCI-CTFSTL-BLF03a', 'MCI-CTFSTL-BLF03b']
    switch_ports: ['Ethernet7', 'Ethernet8']
    profile: L2-Trunk-to-CE
    vlans: 10,11,12,21,22,103,104

# servers:
#   # Name of the defined server.
#   - name: dc1-leaf1-server1
#     # Definition of adapters on the server.
#     adapters:
#         # Name of the server interfaces that will be used in the description of each interface
#       - endpoint_ports: [ PCI1, PCI2 ]
#         # Device ports where the server ports are connected.
#         switch_ports: [ Ethernet5, Ethernet5 ]
#         # Device names where the server ports are connected.
#         switches: [ dc1-leaf1a, dc1-leaf1b ]
#         # VLANs that will be configured on these ports.
#         vlans: 11-12,21-22
#         # Native VLAN to be used on these ports.
#         native_vlan: 4092
#         # L2 mode of the port.
#         mode: trunk
#         # Spanning tree portfast configuration on this port.
#         spanning_tree_portfast: edge
#         # Definition of the pair of ports as port channel.
#         port_channel:
#           # Description of the port channel interface.
#           description: PortChannel dc1-leaf1-server1
#           # Port channel mode for LACP.
#           mode: active

#       - endpoint_ports: [ iLO ]
#         switch_ports: [ Ethernet5 ]
#         switches: [ dc1-leaf1c ]
#         vlans: 11
#         mode: access
#         spanning_tree_portfast: edge

#   - name: dc1-leaf2-server1
#     adapters:
#       - endpoint_ports: [ PCI1, PCI2 ]
#         switch_ports: [ Ethernet5, Ethernet5 ]
#         switches: [ dc1-leaf2a, dc1-leaf2b ]
#         vlans: 11-12,21-22
#         native_vlan: 4092
#         mode: trunk
#         spanning_tree_portfast: edge
#         port_channel:
#           description: PortChannel dc1-leaf2-server1
#           mode: active

#       - endpoint_ports: [ iLO ]
#         switch_ports: [ Ethernet5 ]
#         switches: [ dc1-leaf2c ]
#         vlans: 11
#         mode: access
#         spanning_tree_portfast: edge
