---
# Default gateway used for the management interface
mgmt_gateway: 172.18.102.1

# Turn off wait install
bgp_update_wait_install: false
bgp_update_wait_for_convergence: false

# Spine switch group
spine:
  # Definition of default values that will be configured to all nodes defined in this group
  defaults:
    # Set the relevant platform as each platform has different default values in Ansible AVD
    platform: veos
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 10.255.0.0/27
    # ASN to be used by BGP
    bgp_as: 65100

  # Definition of nodes contained in this group.
  # Specific configuration of device must take place under the node definition. Each node inherits all values defined under 'defaults'
  nodes:
    # Name of the node to be defined (must be consistent with definition in inventory)
    - name: MCI-CTFSTL-SP01
      # Device ID definition. An integer number used for internal calculations (ie. IPv4 address of the loopback_ipv4_pool among others)
      id: 1
      # Management IP to be assigned to the management interface
      mgmt_ip: 172.18.102.20/24
      mac_address: "ac:3d:94:75:1a:62"

    - name: MCI-CTFSTL-SP02
      id: 2
      mgmt_ip: 172.18.102.21/24
      mac_address: "ac:3d:94:75:13:56"

# L3 Leaf switch group
l3leaf:
  defaults:
    # Set the relevant platform as each platform has different default values in Ansible AVD
    platform: veos
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 10.255.0.0/27
    # Offset all assigned loopback IP addresses.
    # Required when the < loopback_ipv4_pool > is same for 2 different node_types (like spine and l3leaf) to avoid over-lapping IPs.
    # For example, set the minimum offset l3leaf.defaults.loopback_ipv4_offset: < total # spine switches > or vice versa.
    loopback_ipv4_offset: 2
    # Definition of pool of IPs to be used as Virtual Tunnel EndPoint (VXLAN origin and destination IPs)
    vtep_loopback_ipv4_pool: 10.255.1.0/27
    # Ansible hostname of the devices used to establish neighborship (IP assignments and BGP peering)
    uplink_switches: ['MCI-CTFSTL-SP01', 'MCI-CTFSTL-SP02']
    # Set uplink interfaces for leafs
    uplink_interfaces: ['Ethernet49/1', 'Ethernet50/1']
    # Definition of pool of IPs to be used in P2P links
    uplink_ipv4_pool: 10.255.255.0/26
    # Definition of pool of IPs to be used for MLAG peer-link connectivity
    mlag_peer_ipv4_pool: 10.255.1.64/27
    # iBGP Peering between MLAG peers
    mlag_peer_l3_ipv4_pool: 10.255.1.96/27
    # Set mlag interfaces for all leafs
    mlag_interfaces: ['Ethernet51/1', 'Ethernet52/1']
    # Virtual router mac for VNIs assigned to Leaf switches in format xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp

  # If two nodes (and only two) are in the same node_group, they will automatically form an MLAG pair
  node_groups:
    # Definition of a node group that will include two devices in MLAG.
    # Definitions under the group will be inherited by both nodes in the group
    - group: DC1_L3_LEAF1
      # ASN to be used by BGP for the group. Both devices in the MLAG pair will use the same BGP ASN
      bgp_as: 65101
      nodes:
        # Definition of hostnames under the node_group
        - name: MCI-CTFSTL-LF01a
          filter:
            tags: ['MCI-CTFSTL-LF01a', 'evpn_services']
          id: 1
          mgmt_ip: 172.18.102.22/24
          mac_address: "ac:3d:94:75:2c:f6"
          uplink_switch_interfaces: ['Ethernet49/1', 'Ethernet49/1']

        - name: MCI-CTFSTL-LF01b
          filter:
            tags: ['MCI-CTFSTL-LF01b', 'evpn_services']
          id: 2
          mgmt_ip: 172.18.102.23/24
          mac_address: "ac:3d:94:75:0f:d0"
          uplink_switch_interfaces: ['Ethernet50/1', 'Ethernet50/1']

    - group: DC1_L3_LEAF2
      bgp_as: 65102
      nodes:
        - name: MCI-CTFSTL-LF02a
          filter:
            tags: ['MCI-CTFSTL-LF02a', 'evpn_services']
          id: 3
          mgmt_ip: 172.18.102.24/24
          mac_address: "ac:3d:94:75:1d:96"
          uplink_switch_interfaces: ['Ethernet51/1', 'Ethernet51/1']

        - name: MCI-CTFSTL-LF02b
          filter:
            tags: ['MCI-CTFSTL-LF02b', 'evpn_services']
          id: 4
          mgmt_ip: 172.18.102.25/24
          mac_address: "ac:3d:94:74:1c:0e"
          uplink_switch_interfaces: ['Ethernet52/1', 'Ethernet52/1']

    - group: DC1_L3_BRD
      bgp_as: 65103
      nodes:
        - name: MCI-CTFSTL-BLF03a
          filter:
            tags: ['MCI-CTFSTL-BLF03a', 'evpn_services']
          id: 5
          mgmt_ip: 172.18.102.26/24
          mac_address: "ac:3d:94:75:30:ce"
          uplink_switch_interfaces: ['Ethernet53/1', 'Ethernet54/1']

        - name: MCI-CTFSTL-BLF03b
          filter:
            tags: ['MCI-CTFSTL-BLF03b', 'evpn_services']
          id: 6
          mgmt_ip: 172.18.102.27/24
          mac_address: "ac:3d:94:75:11:18"
          uplink_switch_interfaces: ['Ethernet54/1', 'Ethernet53/1']


