---
tenants:
  # Definition of tenants. Additional level of abstraction to VRFs
  - name: TENANT1
    # Number used to generate the VNI of each VLAN by adding the VLAN number in this tenant.
    mac_vrf_vni_base: 10000
    vrfs:
      # VRF definitions inside the tenant.
      - name: VRF10
        # VRF VNI definition.
        vrf_vni: 10
        # Enable VTEP Network diagnostics
        # This will create a loopback with virtual source-nat enable to perform diagnostics from the switch.
        vtep_diagnostic:
          # Loopback interface number
          loopback: 10
          # Loopback ip range, a unique ip is derived from this ranged and assigned
          # to each l3 leaf based on it's unique id.
          loopback_ip_range: 10.255.10.0/27
        svis:
          # SVI definitions.
          - id: 11
            tags: ['evpn_services']
            # SVI Description
            name: VRF10_VLAN11
            enabled: true
            # IP anycast gateway to be used in the SVI in every leaf.
            ip_address_virtual: 10.10.11.1/24
          - id: 12
            tags: ['evpn_services']
            name: VRF10_VLAN12
            enabled: true
            ip_address_virtual: 10.10.12.1/24
      - name: VRF11
        vrf_vni: 11
        vtep_diagnostic:
          loopback: 11
          loopback_ip_range: 10.255.11.0/27
        svis:
          - id: 21
            tags: ['evpn_services']
            name: VRF11_VLAN21
            enabled: true
            ip_address_virtual: 10.10.21.1/24
          - id: 22
            tags: ['evpn_services']
            name: VRF11_VLAN22
            enabled: true
            ip_address_virtual: 10.10.22.1/24
      - name: VRFA
        vrf_vni: 12
        vtep_diagnostic:
          loopback: 12
          loopback_ip_range: 10.255.11.0/27
        svis:
          - id: 101
            name: Nadeem_VLAN
            tags: ['MCI-CTFSTL-LF01a']
            enabled: true
            nodes:
                # l3_leaf inventory hostname
              - node: MCI-CTFSTL-LF01a
                ip_address: 10.10.101.102/24
          - id: 111
            name: TheDream_VLAN
            tags: ['MCI-CTFSTL-LF01b']
            enabled: true
            nodes:
                # l3_leaf inventory hostname
              - node: MCI-CTFSTL-LF01b
                ip_address: 10.10.111.102/24
          - id: 102
            name: Joe_VLAN
            tags: ['MCI-CTFSTL-LF02a']
            enabled: true
            nodes:
                # l3_leaf inventory hostname
              - node: MCI-CTFSTL-LF02a
                ip_address: 10.10.102.102/24
          - id: 122
            name: Shmo_VLAN
            tags: ['MCI-CTFSTL-LF02b']
            enabled: true
            nodes:
                # l3_leaf inventory hostname
              - node: MCI-CTFSTL-LF02b
                ip_address: 10.10.122.102/24
          - id: 103
            name: Roddy_VLAN
            tags: ['MCI-CTFSTL-BLF03a']
            enabled: true
            nodes:
                # l3_leaf inventory hostname
              - node: MCI-CTFSTL-BLF03a
                ip_address: 10.10.103.102/24
          - id: 104
            name: Mayday_VLAN
            tags: ['MCI-CTFSTL-BLF03b']
            enabled: true
            nodes:
                # l3_leaf inventory hostname
              - node: MCI-CTFSTL-BLF03b
                ip_address: 10.10.104.102/24

        bgp_peers:
          # Server Leafs
          - ip_address: 10.10.101.101
            remote_as: 65111
            description: CE1_VLAN101
            nodes:
              - MCI-CTFSTL-LF01a
          - ip_address: 10.10.111.101
            remote_as: 65111
            description: CE1_VLAN111
            nodes:
              - MCI-CTFSTL-LF01b
          # DMZ Leafs
          - ip_address: 10.10.102.101
            remote_as: 65122
            description: CE2_VLAN102
            nodes:
              - MCI-CTFSTL-LF02a
          - ip_address: 10.10.122.101
            remote_as: 65122
            description: CE2_VLAN122
            nodes:
              - MCI-CTFSTL-LF02b
          # Border Leafs
          - ip_address: 10.10.103.101
            remote_as: 65133
            description: CE3_VLAN103
            nodes:
              - MCI-CTFSTL-BLF03a
          - ip_address: 10.10.104.101
            remote_as: 65144
            description: CE4_VLAN104
            nodes:
              - MCI-CTFSTL-BLF03b
    #l2vlans:
      # These are pure L2 vlans. They do not have a SVI defined in the l3leafs and they will be bridged inside the VXLAN fabric
     # - id: 3401
      #  name: L2_VLAN3401
      #- id: 3402
      #  name: L2_VLAN3402
